
-- --------------------------------------------------------

--
-- Структура таблицы `concurs_lenta`
--

CREATE TABLE `concurs_lenta` (
  `id` mediumint(9) NOT NULL,
  `pid` mediumint(9) NOT NULL,
  `rate` mediumint(9) NOT NULL,
  `domain` mediumint(9) NOT NULL DEFAULT '0' COMMENT 'Домен',
  `data` varchar(15) NOT NULL COMMENT 'дата создания',
  `astat` int(1) NOT NULL DEFAULT '0' COMMENT 'разрешить автопубликацию',
  `adata` varchar(15) NOT NULL DEFAULT '' COMMENT 'дата автопубликации',
  `stat` int(1) NOT NULL DEFAULT '0',
  `seen` mediumint(9) NOT NULL,
  `likes` mediumint(9) NOT NULL,
  `dislikes` mediumint(9) NOT NULL,
  `seens` mediumint(9) NOT NULL,
  `name` varchar(255) NOT NULL COMMENT 'заголовок материала',
  `title` varchar(255) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `lid` text NOT NULL COMMENT 'лид материала',
  `text` text NOT NULL COMMENT 'основное содержание',
  `alttext` mediumtext,
  `endtext` text NOT NULL COMMENT 'заключительный текст',
  `pic` varchar(255) NOT NULL COMMENT 'основная картинка',
  `uid` mediumint(9) NOT NULL,
  `adv` text NOT NULL,
  `pay` text NOT NULL,
  `kw` varchar(255) NOT NULL,
  `ds` varchar(255) NOT NULL,
  `picxy` text NOT NULL COMMENT 'координаты кропа основной картинки',
  `picauth` varchar(255) NOT NULL,
  `realinfo` varchar(255) NOT NULL COMMENT 'информационный источник',
  `cens` varchar(255) NOT NULL COMMENT 'возрастное ограничение',
  `comments` int(1) NOT NULL DEFAULT '0' COMMENT 'статус комментариев',
  `comcount` mediumint(9) NOT NULL DEFAULT '0' COMMENT 'количество комментариев',
  `voting` int(1) NOT NULL DEFAULT '0' COMMENT 'статус голосования',
  `votingend` varchar(15) NOT NULL COMMENT 'дата окончания голосования',
  `elemsstyle` int(1) NOT NULL DEFAULT '3' COMMENT 'стиль номинантов в голосовании',
  `winnerscount` int(1) NOT NULL DEFAULT '1' COMMENT 'количество победителей',
  `tags` text NOT NULL COMMENT 'теги материала',
  `yarss` int(1) NOT NULL DEFAULT '0' COMMENT 'В яндекс',
  `mailrss` int(1) NOT NULL DEFAULT '0' COMMENT 'в мэйл',
  `tavto` int(1) NOT NULL DEFAULT '0' COMMENT 'в тизеры тавто',
  `onind` int(1) NOT NULL DEFAULT '0' COMMENT 'в телевизор',
  `spec` int(1) NOT NULL DEFAULT '0' COMMENT 'спец. размещение',
  `promo` int(1) NOT NULL DEFAULT '0' COMMENT 'коммерческая новость',
  `spromo` varchar(1) NOT NULL,
  `redak` int(1) NOT NULL DEFAULT '0' COMMENT 'Редакционная колонка',
  `gis` int(1) NOT NULL DEFAULT '0' COMMENT 'Отправить гисметео',
  `mailtizer` int(1) NOT NULL DEFAULT '0' COMMENT 'в тизер Mail',
  `preview_mobile` tinyint(1) NOT NULL COMMENT 'Preview in mobile'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
